import Header from '@/components/Header/page';

export const metadata = {
    title: 'Mangoo - CRM',
    description: 'Generated by Hakan Sivritepe',
};

export default function Layout({ children }) {
    return (
        <>
            <Header />
            {children}
        </>
    );
}
